### ISSUE TITLE
FIXTURES_URL 404s

### ISSUE THREAD

**Issue by rgarner** [fatbusinessman/football-calendar#1]
It no longer works.

Perhaps we could outsource the fix to Crawley Town?

(I already have my coat)

**Comment by dhwthompson** [comment]
Turns out I had a commit tucked away in my local version (5d01114d0a52252cb8eef92cae143053f78106ef) that fixes this issue through the medium of ~interpretive dance~ **environment variables**. As a bonus, that turns this into a more general-purpose calendar filter. Given Crawley Town seems to use the same white-label site as Cambridge United, that should mean you can set up your own deployment for those fixtures instead, should you feel the urge.

For reference, the values I’m using at the moment are:

```
FIXTURES_URL='https://www.stanza.co/api/schedules/cambridgeunited/cambridgeunited.ics'
HOME_LOCATION='The Abbey Stadium'
```

**Comment by dhwthompson** [comment]
Also, thanks for pointing out the issue. I no longer live close enough to the stadium that I need to keep track of when the games are, hence not spotting the problem myself.

**Comment by rgarner** [comment]
I'm afraid I was only really using this issue to make a poorly-conceived
Crawley Town joke.
